import { Inter } from "next/font/google"
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "../_components/Sidebar";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-grow p-6">
            <SidebarTrigger className="ml-4 mb-8" />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
